USE customer_behavior;

SELECT * FROM customer_table LIMIT 20;


# Q1. WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS. FEMALE CUSTOMERS?
SELECT gender, 
       SUM(purchase_amount) AS revenue
FROM customer_table
GROUP BY gender;

# Q2. WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT?
SELECT customer_id, purchase_amount
FROM customer_table
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount) 
        FROM customer_table
      );

# Q3. WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING?
SELECT item_purchased,
       ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS average_product_rating
FROM customer_table
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS DECIMAL(10,2))) DESC
LIMIT 5;

# Q4. COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING.
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS average_spend
FROM customer_table
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

# Q5. DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_table
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

# Q6. WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNTS APPLIED?
SELECT item_purchased,
       ROUND(
            100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
            / COUNT(*), 
       2) AS discount_rate
FROM customer_table
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# Q7. SEGMENT CUSTOMERS INTO NEW, RETURNING, AND LOYAL AND SHOW THE COUNT OF EACH SEGMENT.
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
           CASE 
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer_table
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

# Q8. WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_table
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

# Q9. ARE CUSTOMERS WITH MORE THAN 5 PREVIOUS PURCHASES MORE LIKELY TO SUBSCRIBE?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_table
WHERE previous_purchases > 5
GROUP BY subscription_status;

# Q10. WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer_table
GROUP BY age_group
ORDER BY total_revenue DESC;